# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Julkisten palveluiden parhaat käytännöt
email: info@julkictlab.fi
description: > # this means to ignore newlines until "baseurl:"
  Julkishallinnon parhaita käytäntöjä ja suosituksia palvelukehityksen tueksi
baseurl: "/julkictlab-best-practices" # the subpath of your site, e.g. /blog
url: "http://csc-it-center-for-science.github.io" # the base hostname & protocol for your site
twitter_username: julkictlab
github_username:  CSC-IT-Center-for-Science

# Build settings
markdown: kramdown
